# Display message to the standard output
print("System Failure Iminent!\nSystem reboot has been initiated...")
print("...rebooting sensory system\n...rebooting output motors\n...rebooting hover engine")
print("\n\"I am Beep!\"")
print("################################")
print("#                              #")
print("#     _(\    |@@|              #")
print("#    (__/\__ \--/ __           #")
print("#       \___|----|  |   __     #")
print("#           \ }{ /\ )_ / _\    #")
print("#           /\__/\ \__O (__    #")
print("#          (--/\--)    \__/    #")
print("#          _)(  )(_            #")
print("#         `---''---`           #")
print("#                              #")
print("################################")